import React, { useEffect, useState } from "react";
import { useDispatch } from "react-redux";
import dynamic from "next/dynamic";
import Head from "next/head";

const StateController = dynamic(() => import("@/components/stateController"), {
  loading: () => <></>,
});

import { setLocalStage } from "@/utils/reduxConfig";
import { getLocalStorage } from "@/utils/common";

export default function Home() {
  const [localStageIndex, setLocalStageIndex] = useState<number>(0);
  const dispatch = useDispatch();

  useEffect(() => {
    if (window !== undefined) {
      const store = getLocalStorage("STAGE");
      if (store) {
        const stage: number = getLocalStorage("STAGE")["stage"];
        setLocalStageIndex(stage);
        dispatch(setLocalStage(stage));
      } else {
        setLocalStageIndex(1);
        dispatch(setLocalStage(1));
      }
    }
  }, [dispatch]);

  return (
    <>
      <Head>
        <title>Memories</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {localStageIndex !== 0 ? <StateController /> : null}
    </>
  );
}
