import React from 'react';
import Head from 'next/head';

import StateController from '@/components/statecontroller';

export default function Home() {
  return (
    <>
      <Head>
        <title>Memories</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <StateController />
    </>
  );
}
